/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tesframe;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Barang extends javax.swing.JPanel {
    koneksi db = new koneksi();
    DefaultTableModel model = new DefaultTableModel();
    
    public Barang(String n) {
        initComponents();
        
        aturColumnn();
        aturBariss();
        
    }
    public void aturColumnn(){
        model.addColumn("ID");
        model.addColumn("Nama Barang");
        model.addColumn("Jenis Barang");
        model.addColumn("Jumlah Barang");
        model.addColumn("Harga");
        model.addColumn("Satuan");
        tb_b.setModel(model);
        
    }
     public void aturBariss(){
        ResultSet hasil = db.ambilData("SELECT * FROM barang");
        try {
            while(hasil.next()) {
                model.addRow(new Object[]{hasil.getString("idbarang"), hasil.getString("nama_barang"),hasil.getString("jenis_barang"),hasil.getString("jumlah_barang"),hasil.getString("harga"),hasil.getString("satuan")});
                
            }
             tb_b.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_konten_Barang = new javax.swing.JPanel();
        Tbl_Barang_Katalog = new javax.swing.JPanel();
        Jd_Barang = new javax.swing.JLabel();
        Lb_katalog = new javax.swing.JLabel();
        Btn_Tambah = new rojerusan.RSMaterialButtonRectangle();
        Btn_Update = new rojerusan.RSMaterialButtonRectangle();
        Btn_Hapus = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_b = new javax.swing.JTable();
        Tbl_Barang_Tambah = new javax.swing.JPanel();
        Jd_Barang1 = new javax.swing.JLabel();
        Btn_Simpan = new rojerusan.RSMaterialButtonRectangle();
        Btn_Batal = new rojerusan.RSMaterialButtonRectangle();
        Lb_Id = new javax.swing.JLabel();
        idb = new javax.swing.JTextField();
        Lb_Nama = new javax.swing.JLabel();
        nb = new javax.swing.JTextField();
        Lb_Jenis = new javax.swing.JLabel();
        jb = new javax.swing.JTextField();
        Lb_Jumlah = new javax.swing.JLabel();
        jmb = new javax.swing.JTextField();
        Lb_Satuan = new javax.swing.JLabel();
        sb = new javax.swing.JTextField();
        Lb_Harga = new javax.swing.JLabel();
        hb = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Jd_Barang2 = new javax.swing.JLabel();
        Tbl_Update_Barang = new javax.swing.JPanel();
        Btn_Tambah1 = new rojerusan.RSMaterialButtonRectangle();
        Btn_Kurangi = new rojerusan.RSMaterialButtonRectangle();
        Btn_Kembali = new rojerusan.RSMaterialButtonRectangle();
        jLabel3 = new javax.swing.JLabel();
        ib = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ujb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        unb = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        uj = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ust = new javax.swing.JTextField();
        u_hg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jd_Barang4 = new javax.swing.JLabel();
        Jd_Barang5 = new javax.swing.JLabel();
        Jd_Barang6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.CardLayout());

        pn_konten_Barang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_konten_BarangMouseClicked(evt);
            }
        });
        pn_konten_Barang.setLayout(new java.awt.CardLayout());

        Tbl_Barang_Katalog.setBackground(new java.awt.Color(255, 255, 255));

        Jd_Barang.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Barang.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Barang.setText("Barang");

        Lb_katalog.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_katalog.setText("Katalog");

        Btn_Tambah.setText("Tambah");
        Btn_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_TambahActionPerformed(evt);
            }
        });

        Btn_Update.setBackground(new java.awt.Color(0, 204, 0));
        Btn_Update.setText("Update");
        Btn_Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_UpdateActionPerformed(evt);
            }
        });

        Btn_Hapus.setBackground(new java.awt.Color(255, 51, 0));
        Btn_Hapus.setText("Hapus");
        Btn_Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusActionPerformed(evt);
            }
        });

        tb_b.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_b);

        javax.swing.GroupLayout Tbl_Barang_KatalogLayout = new javax.swing.GroupLayout(Tbl_Barang_Katalog);
        Tbl_Barang_Katalog.setLayout(Tbl_Barang_KatalogLayout);
        Tbl_Barang_KatalogLayout.setHorizontalGroup(
            Tbl_Barang_KatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tbl_Barang_KatalogLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Tbl_Barang_KatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tbl_Barang_KatalogLayout.createSequentialGroup()
                        .addComponent(Lb_katalog, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Tbl_Barang_KatalogLayout.createSequentialGroup()
                        .addGroup(Tbl_Barang_KatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tbl_Barang_KatalogLayout.createSequentialGroup()
                                .addComponent(Btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)
                                .addComponent(Btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 944, Short.MAX_VALUE)
                            .addComponent(Jd_Barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(30, 30, 30))))
        );
        Tbl_Barang_KatalogLayout.setVerticalGroup(
            Tbl_Barang_KatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Barang_KatalogLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(Jd_Barang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64)
                .addGroup(Tbl_Barang_KatalogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_Update, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addComponent(Lb_katalog)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1)
                .addGap(58, 58, 58))
        );

        pn_konten_Barang.add(Tbl_Barang_Katalog, "card2");

        Tbl_Barang_Tambah.setBackground(new java.awt.Color(255, 255, 255));

        Jd_Barang1.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_Barang1.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Barang1.setText("Tambah Barang");

        Btn_Simpan.setBackground(new java.awt.Color(0, 204, 0));
        Btn_Simpan.setText("Simpan");
        Btn_Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_SimpanActionPerformed(evt);
            }
        });

        Btn_Batal.setBackground(new java.awt.Color(255, 51, 0));
        Btn_Batal.setText("Batal");
        Btn_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BatalActionPerformed(evt);
            }
        });

        Lb_Id.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Id.setText("ID Barang");

        idb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idbActionPerformed(evt);
            }
        });

        Lb_Nama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Nama.setText("Nama Barang");

        nb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbActionPerformed(evt);
            }
        });

        Lb_Jenis.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Jenis.setText("Jenis Barang");

        jb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbActionPerformed(evt);
            }
        });

        Lb_Jumlah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Jumlah.setText("Jumlah Barang");

        jmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmbActionPerformed(evt);
            }
        });

        Lb_Satuan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Satuan.setText("Satuan Barang");

        sb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sbActionPerformed(evt);
            }
        });

        Lb_Harga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Harga.setText("Harga Barang");

        hb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText(">");

        Jd_Barang2.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Barang2.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Barang2.setText("Barang");

        javax.swing.GroupLayout Tbl_Barang_TambahLayout = new javax.swing.GroupLayout(Tbl_Barang_Tambah);
        Tbl_Barang_Tambah.setLayout(Tbl_Barang_TambahLayout);
        Tbl_Barang_TambahLayout.setHorizontalGroup(
            Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(Jd_Barang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(Jd_Barang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(676, 676, 676))
            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                        .addComponent(Btn_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Btn_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                        .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nb, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(idb)
                                .addComponent(Lb_Nama, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Lb_Id, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jb, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(Lb_Jenis, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jmb, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(Lb_Jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(sb, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(Lb_Satuan, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(hb, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                .addComponent(Lb_Harga, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(170, 170, 170))))
        );
        Tbl_Barang_TambahLayout.setVerticalGroup(
            Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                        .addComponent(Lb_Harga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(hb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                        .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(Jd_Barang1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(Jd_Barang2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(63, 63, 63)
                        .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Btn_Simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Btn_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                .addGroup(Tbl_Barang_TambahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                        .addComponent(Lb_Id)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(idb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                        .addComponent(Lb_Jumlah)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jmb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(Lb_Nama)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Tbl_Barang_TambahLayout.createSequentialGroup()
                                .addComponent(Lb_Satuan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(Lb_Jenis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(282, 282, 282))
        );

        pn_konten_Barang.add(Tbl_Barang_Tambah, "card2");

        Tbl_Update_Barang.setBackground(new java.awt.Color(255, 255, 255));

        Btn_Tambah1.setBackground(new java.awt.Color(0, 153, 255));
        Btn_Tambah1.setText("Tambah");
        Btn_Tambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Tambah1ActionPerformed(evt);
            }
        });

        Btn_Kurangi.setBackground(new java.awt.Color(255, 153, 0));
        Btn_Kurangi.setText("Kurangi");
        Btn_Kurangi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KurangiActionPerformed(evt);
            }
        });

        Btn_Kembali.setBackground(new java.awt.Color(204, 0, 0));
        Btn_Kembali.setText("Kembali");
        Btn_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_KembaliActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel3.setText("ID Barang");

        ib.setEnabled(false);
        ib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel4.setText("Jumlah Barang");

        ujb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujbActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel5.setText("Nama Barang");

        unb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unbActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel6.setText("Jenis");

        uj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ujActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel7.setText("Satuan");

        ust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ustActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        jLabel2.setText("Harga");

        Jd_Barang4.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Barang4.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Barang4.setText(">");

        Jd_Barang5.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Barang5.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Barang5.setText("Barang");

        Jd_Barang6.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Barang6.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Barang6.setText("Update Barang");

        javax.swing.GroupLayout Tbl_Update_BarangLayout = new javax.swing.GroupLayout(Tbl_Update_Barang);
        Tbl_Update_Barang.setLayout(Tbl_Update_BarangLayout);
        Tbl_Update_BarangLayout.setHorizontalGroup(
            Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Tbl_Update_BarangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Update_BarangLayout.createSequentialGroup()
                        .addComponent(Btn_Tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(60, 60, 60)
                        .addComponent(Btn_Kurangi, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addGap(60, 60, 60)
                        .addComponent(Btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addGroup(Tbl_Update_BarangLayout.createSequentialGroup()
                        .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ujb, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(Tbl_Update_BarangLayout.createSequentialGroup()
                                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(ib, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(88, 88, 88)
                                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(unb, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(uj, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 47, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel7)
                        .addComponent(ust, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                        .addComponent(u_hg))
                    .addComponent(jLabel2))
                .addGap(206, 206, 206))
            .addGroup(Tbl_Update_BarangLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(Jd_Barang5, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Jd_Barang4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Jd_Barang6, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Tbl_Update_BarangLayout.setVerticalGroup(
            Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Update_BarangLayout.createSequentialGroup()
                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Update_BarangLayout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(u_hg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(Tbl_Update_BarangLayout.createSequentialGroup()
                        .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Tbl_Update_BarangLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Jd_Barang4)
                                    .addComponent(Jd_Barang6)
                                    .addComponent(Jd_Barang5))
                                .addGap(48, 48, 48)
                                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Btn_Tambah1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Kurangi, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Btn_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Update_BarangLayout.createSequentialGroup()
                                .addGap(222, 222, 222)
                                .addGroup(Tbl_Update_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Update_BarangLayout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(unb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Tbl_Update_BarangLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ust, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ujb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(846, 846, 846))
        );

        pn_konten_Barang.add(Tbl_Update_Barang, "card2");

        add(pn_konten_Barang, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void pn_konten_BarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_konten_BarangMouseClicked
        
    }//GEN-LAST:event_pn_konten_BarangMouseClicked

    private void nbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbActionPerformed

    private void jbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbActionPerformed

    private void jmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmbActionPerformed

    private void sbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sbActionPerformed

    private void hbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hbActionPerformed

    private void Btn_SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_SimpanActionPerformed
        String id = idb.getText();
        String nama = nb.getText();
        String jenis = jb.getText();
        String jumlah = jmb.getText();
        String satuan = sb.getText();
        String harga = hb.getText();
        
        db.aksi("INSERT INTO barang VALUES ('" + id + "','" + nama + "','"+jenis+"','"+jumlah+"','"+harga+"','"+satuan+"')");
         model.setRowCount(0);
         tb_b.setModel(model);
         aturBariss();
        pn_konten_Barang.removeAll();
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
        
        pn_konten_Barang.add(Tbl_Barang_Katalog);
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
    }//GEN-LAST:event_Btn_SimpanActionPerformed

    private void Btn_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BatalActionPerformed
        pn_konten_Barang.removeAll();
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
        
        pn_konten_Barang.add(Tbl_Barang_Katalog);
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
    }//GEN-LAST:event_Btn_BatalActionPerformed

    private void Btn_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_TambahActionPerformed
        pn_konten_Barang.removeAll();
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
        
        pn_konten_Barang.add(Tbl_Barang_Tambah);
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
    }//GEN-LAST:event_Btn_TambahActionPerformed

    private void idbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idbActionPerformed

    private void Btn_HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusActionPerformed
        int Row = tb_b.getSelectedRow();
    String ID = (String) tb_b.getValueAt(Row, 0);
    db.aksi("DELETE FROM barang WHERE idbarang='"+ID+"'");
    model.setRowCount(0);
    tb_b.setModel(model);
    aturBariss();
    }//GEN-LAST:event_Btn_HapusActionPerformed

    private void Btn_UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_UpdateActionPerformed
        int selectedRow = tb_b.getSelectedRow();
        //System.out.println(tb_b.getValueAt(selectedRow, 0));
        //Barang data = new Barang(String.valueOf(tb_b.getValueAt(selectedRow, 0)));
        ib.setText(String.valueOf(tb_b.getValueAt(selectedRow, 0)));
        unb.setText(String.valueOf(tb_b.getValueAt(selectedRow, 1)));
        uj.setText(String.valueOf(tb_b.getValueAt(selectedRow, 2)));
        ust.setText(String.valueOf(tb_b.getValueAt(selectedRow, 5)));
        ujb.setText(String.valueOf(tb_b.getValueAt(selectedRow, 3)));
        u_hg.setText(String.valueOf(tb_b.getValueAt(selectedRow, 4)));
        
        pn_konten_Barang.removeAll();
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
        
        pn_konten_Barang.add(Tbl_Update_Barang);
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();     
    }//GEN-LAST:event_Btn_UpdateActionPerformed

    private void Btn_Tambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Tambah1ActionPerformed
         int Row = tb_b.getSelectedRow();
    String ID = (String) tb_b.getValueAt(Row, 0);
    db.aksi("UPDATE barang SET nama_barang = '"+unb.getText()+"',jenis_barang = '"+uj.getText()+"',jumlah_barang = '"+ujb.getText()+"',harga = '"+u_hg.getText()+"' WHERE idbarang = '"+ib.getText()+"'");
    model.setRowCount(0);
    tb_b.setModel(model);
    aturBariss();
    
     pn_konten_Barang.removeAll();
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
        
        pn_konten_Barang.add(Tbl_Barang_Katalog);
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
    }//GEN-LAST:event_Btn_Tambah1ActionPerformed

    private void Btn_KurangiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KurangiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_KurangiActionPerformed

    private void Btn_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_KembaliActionPerformed
        pn_konten_Barang.removeAll();
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();
        
        pn_konten_Barang.add(Tbl_Barang_Katalog);
        pn_konten_Barang.repaint();
        pn_konten_Barang.revalidate();     
    }//GEN-LAST:event_Btn_KembaliActionPerformed

    private void ibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibActionPerformed

    private void ujbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ujbActionPerformed

    private void unbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unbActionPerformed

    private void ujActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ujActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ujActionPerformed

    private void ustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ustActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ustActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Btn_Batal;
    private rojerusan.RSMaterialButtonRectangle Btn_Hapus;
    private rojerusan.RSMaterialButtonRectangle Btn_Kembali;
    private rojerusan.RSMaterialButtonRectangle Btn_Kurangi;
    private rojerusan.RSMaterialButtonRectangle Btn_Simpan;
    private rojerusan.RSMaterialButtonRectangle Btn_Tambah;
    private rojerusan.RSMaterialButtonRectangle Btn_Tambah1;
    private rojerusan.RSMaterialButtonRectangle Btn_Update;
    private javax.swing.JLabel Jd_Barang;
    private javax.swing.JLabel Jd_Barang1;
    private javax.swing.JLabel Jd_Barang2;
    private javax.swing.JLabel Jd_Barang4;
    private javax.swing.JLabel Jd_Barang5;
    private javax.swing.JLabel Jd_Barang6;
    private javax.swing.JLabel Lb_Harga;
    private javax.swing.JLabel Lb_Id;
    private javax.swing.JLabel Lb_Jenis;
    private javax.swing.JLabel Lb_Jumlah;
    private javax.swing.JLabel Lb_Nama;
    private javax.swing.JLabel Lb_Satuan;
    private javax.swing.JLabel Lb_katalog;
    private javax.swing.JPanel Tbl_Barang_Katalog;
    private javax.swing.JPanel Tbl_Barang_Tambah;
    private javax.swing.JPanel Tbl_Update_Barang;
    private javax.swing.JTextField hb;
    private javax.swing.JTextField ib;
    private javax.swing.JTextField idb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jb;
    private javax.swing.JTextField jmb;
    private javax.swing.JTextField nb;
    private javax.swing.JPanel pn_konten_Barang;
    private javax.swing.JTextField sb;
    private javax.swing.JTable tb_b;
    private javax.swing.JTextField u_hg;
    private javax.swing.JTextField uj;
    private javax.swing.JTextField ujb;
    private javax.swing.JTextField unb;
    private javax.swing.JTextField ust;
    // End of variables declaration//GEN-END:variables
}
