/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tesframe;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author acer
 */
public class Beranda extends javax.swing.JPanel {
    koneksi db = new koneksi();
    DefaultTableModel model1 = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    DefaultTableModel model3 = new DefaultTableModel();
    
    public Beranda() {
        initComponents();
        aturColumn1();
        aturBaris();
        
        aturColumn2();
        aturBariss();
        
        aturColumn3();
        aturBarisss();
    }
    public void aturColumn1(){
        model1.addColumn("ID");
        model1.addColumn("Nama Barang");
        model1.addColumn("Jenis Barang");
        model1.addColumn("Jumlah Barang");
        model1.addColumn("Harga");
        model1.addColumn("Satuan");
        tb_b.setModel(model1);
        model1.setRowCount(0);
    }
    public void aturColumn2(){
        model2.addColumn("ID");
        model2.addColumn("Nama Pemesan");
        
        model2.addColumn("Jumlah Pesanan");
        model2.addColumn("Tanggal Pesanan");
        model2.addColumn("Alamat");
        model2.addColumn("No Telepon");
        model2.addColumn("Harga");
        model2.addColumn("Status");
        model2.addColumn("Nama Barang");
        tb_b2.setModel(model2);
        model2.setRowCount(0);
    }
    public void aturColumn3(){
        model3.addColumn("ID");
        model3.addColumn("Tanggal Laporan");
        model3.addColumn("Jenis Laporan");
        tb_b3.setModel(model3);
        model3.setRowCount(0);
    }
    public void aturBaris(){
        ResultSet hasil = db.ambilData("SELECT * FROM barang");
        try {
            while(hasil.next()) {
                model1.addRow(new Object[]{hasil.getString("idbarang"), hasil.getString("nama_barang"),hasil.getString("jenis_barang"),hasil.getString("jumlah_barang"),hasil.getString("harga"),hasil.getString("satuan")});
           
            }
             tb_b.setModel(model1);
        } catch (SQLException ex) {
            Logger.getLogger(Barang.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    public void aturBariss(){
        ResultSet hasil = db.ambilData("SELECT * FROM pemesan");
        try {
            while(hasil.next()) {
                model2.addRow(new Object[]{hasil.getString("idpemesan"), hasil.getString("nama_pemesan"),hasil.getString("nama_barang"),hasil.getString("jumlah_barang"),hasil.getString("tgl"), hasil.getString("alamat"), hasil.getString("no_tlp"),hasil.getString("harga"),hasil.getString("Status")});
                
            }
             tb_b2.setModel(model2);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    
    }
    public void aturBarisss(){
        ResultSet hasil = db.ambilData("SELECT * FROM laporan");
        try {
            while(hasil.next()) {
                model3.addRow(new Object[]{hasil.getString("idlaporan"), hasil.getString("tgl_laporan"),hasil.getString("detail_laporan")});
                
            }
             tb_b3.setModel(model3);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_konten_Beranda = new javax.swing.JPanel();
        Beranda_DataBarang = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_b = new javax.swing.JTable();
        Jd_Beranda1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Jd_DataBarang = new javax.swing.JLabel();
        Btn_DataBarang = new rojerusan.RSMaterialButtonRectangle();
        Btn_DataPemesan = new rojerusan.RSMaterialButtonRectangle();
        Btn_DataLaporan = new rojerusan.RSMaterialButtonRectangle();
        Beranda_DataPemesan = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tb_b2 = new javax.swing.JTable();
        Jd_Beranda2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Jd_DataPemesan = new javax.swing.JLabel();
        Btn_DataBarang1 = new rojerusan.RSMaterialButtonRectangle();
        Btn_DataPemesan1 = new rojerusan.RSMaterialButtonRectangle();
        Btn_DataLaporan1 = new rojerusan.RSMaterialButtonRectangle();
        Beranda_DataLaporan = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tb_b3 = new javax.swing.JTable();
        Btn_DataBarang2 = new rojerusan.RSMaterialButtonRectangle();
        Btn_DataPemesan2 = new rojerusan.RSMaterialButtonRectangle();
        Btn_DataLaporan2 = new rojerusan.RSMaterialButtonRectangle();
        Jd_Beranda4 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Jd_DataPemesan1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));

        pn_konten_Beranda.setBackground(new java.awt.Color(255, 255, 255));

        Beranda_DataBarang.setBackground(new java.awt.Color(255, 255, 255));

        tb_b.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tb_b);

        Jd_Beranda1.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Beranda1.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Beranda1.setText("Beranda");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setText(">");

        Jd_DataBarang.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_DataBarang.setForeground(new java.awt.Color(0, 31, 63));
        Jd_DataBarang.setText("Data Barang");

        Btn_DataBarang.setBackground(new java.awt.Color(0, 100, 102));
        Btn_DataBarang.setText("Data barang");
        Btn_DataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataBarangActionPerformed(evt);
            }
        });

        Btn_DataPemesan.setBackground(new java.awt.Color(255, 100, 0));
        Btn_DataPemesan.setText("Data pemesan");
        Btn_DataPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataPemesanActionPerformed(evt);
            }
        });

        Btn_DataLaporan.setBackground(new java.awt.Color(153, 0, 0));
        Btn_DataLaporan.setText("Data laporan");
        Btn_DataLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataLaporanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Beranda_DataBarangLayout = new javax.swing.GroupLayout(Beranda_DataBarang);
        Beranda_DataBarang.setLayout(Beranda_DataBarangLayout);
        Beranda_DataBarangLayout.setHorizontalGroup(
            Beranda_DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Beranda_DataBarangLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Beranda_DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 916, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Beranda_DataBarangLayout.createSequentialGroup()
                        .addComponent(Jd_Beranda1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(Jd_DataBarang))
                    .addGroup(Beranda_DataBarangLayout.createSequentialGroup()
                        .addComponent(Btn_DataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Btn_DataPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Btn_DataLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        Beranda_DataBarangLayout.setVerticalGroup(
            Beranda_DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Beranda_DataBarangLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Beranda_DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Beranda1)
                    .addComponent(jLabel1)
                    .addComponent(Jd_DataBarang))
                .addGap(35, 35, 35)
                .addGroup(Beranda_DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_DataBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_DataPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_DataLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
                .addGap(147, 147, 147))
        );

        Beranda_DataPemesan.setBackground(new java.awt.Color(255, 255, 255));

        tb_b2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(tb_b2);

        Jd_Beranda2.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Beranda2.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Beranda2.setText("Beranda");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setText(">");

        Jd_DataPemesan.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_DataPemesan.setForeground(new java.awt.Color(0, 31, 63));
        Jd_DataPemesan.setText("Data Pemesan");

        Btn_DataBarang1.setBackground(new java.awt.Color(0, 100, 102));
        Btn_DataBarang1.setText("Data barang");
        Btn_DataBarang1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataBarang1ActionPerformed(evt);
            }
        });

        Btn_DataPemesan1.setBackground(new java.awt.Color(255, 100, 0));
        Btn_DataPemesan1.setText("Data pemesan");
        Btn_DataPemesan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataPemesan1ActionPerformed(evt);
            }
        });

        Btn_DataLaporan1.setBackground(new java.awt.Color(153, 0, 0));
        Btn_DataLaporan1.setText("Data laporan");
        Btn_DataLaporan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataLaporan1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Beranda_DataPemesanLayout = new javax.swing.GroupLayout(Beranda_DataPemesan);
        Beranda_DataPemesan.setLayout(Beranda_DataPemesanLayout);
        Beranda_DataPemesanLayout.setHorizontalGroup(
            Beranda_DataPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Beranda_DataPemesanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Beranda_DataPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 892, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Beranda_DataPemesanLayout.createSequentialGroup()
                        .addComponent(Jd_Beranda2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(Jd_DataPemesan))
                    .addGroup(Beranda_DataPemesanLayout.createSequentialGroup()
                        .addComponent(Btn_DataBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Btn_DataPemesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Btn_DataLaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        Beranda_DataPemesanLayout.setVerticalGroup(
            Beranda_DataPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Beranda_DataPemesanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Beranda_DataPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Beranda2)
                    .addComponent(jLabel2)
                    .addComponent(Jd_DataPemesan))
                .addGap(35, 35, 35)
                .addGroup(Beranda_DataPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_DataBarang1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_DataPemesan1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_DataLaporan1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addGap(118, 118, 118))
        );

        Beranda_DataLaporan.setBackground(new java.awt.Color(255, 255, 255));

        tb_b3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tb_b3);

        Btn_DataBarang2.setBackground(new java.awt.Color(0, 100, 102));
        Btn_DataBarang2.setText("Data barang");
        Btn_DataBarang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_DataBarang2MouseClicked(evt);
            }
        });
        Btn_DataBarang2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataBarang2ActionPerformed(evt);
            }
        });

        Btn_DataPemesan2.setBackground(new java.awt.Color(255, 100, 0));
        Btn_DataPemesan2.setText("Data pemesan");
        Btn_DataPemesan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataPemesan2ActionPerformed(evt);
            }
        });

        Btn_DataLaporan2.setBackground(new java.awt.Color(153, 0, 0));
        Btn_DataLaporan2.setText("Data laporan");
        Btn_DataLaporan2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DataLaporan2ActionPerformed(evt);
            }
        });

        Jd_Beranda4.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Beranda4.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Beranda4.setText("Beranda");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText(">");

        Jd_DataPemesan1.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_DataPemesan1.setForeground(new java.awt.Color(0, 31, 63));
        Jd_DataPemesan1.setText("Data Laporan");

        javax.swing.GroupLayout Beranda_DataLaporanLayout = new javax.swing.GroupLayout(Beranda_DataLaporan);
        Beranda_DataLaporan.setLayout(Beranda_DataLaporanLayout);
        Beranda_DataLaporanLayout.setHorizontalGroup(
            Beranda_DataLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Beranda_DataLaporanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Beranda_DataLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 928, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(Beranda_DataLaporanLayout.createSequentialGroup()
                        .addComponent(Jd_Beranda4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Jd_DataPemesan1))
                    .addGroup(Beranda_DataLaporanLayout.createSequentialGroup()
                        .addComponent(Btn_DataBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Btn_DataPemesan2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(Btn_DataLaporan2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(60, 60, 60))
        );
        Beranda_DataLaporanLayout.setVerticalGroup(
            Beranda_DataLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Beranda_DataLaporanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Beranda_DataLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Beranda4)
                    .addComponent(jLabel4)
                    .addComponent(Jd_DataPemesan1))
                .addGap(35, 35, 35)
                .addGroup(Beranda_DataLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_DataBarang2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_DataPemesan2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Btn_DataLaporan2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                .addGap(175, 175, 175))
        );

        javax.swing.GroupLayout pn_konten_BerandaLayout = new javax.swing.GroupLayout(pn_konten_Beranda);
        pn_konten_Beranda.setLayout(pn_konten_BerandaLayout);
        pn_konten_BerandaLayout.setHorizontalGroup(
            pn_konten_BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beranda_DataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_konten_BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_konten_BerandaLayout.createSequentialGroup()
                    .addComponent(Beranda_DataPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pn_konten_BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_konten_BerandaLayout.createSequentialGroup()
                    .addComponent(Beranda_DataLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        pn_konten_BerandaLayout.setVerticalGroup(
            pn_konten_BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Beranda_DataBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pn_konten_BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_konten_BerandaLayout.createSequentialGroup()
                    .addComponent(Beranda_DataPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(pn_konten_BerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_konten_BerandaLayout.createSequentialGroup()
                    .addComponent(Beranda_DataLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_konten_Beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pn_konten_Beranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_DataLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataLaporanActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataLaporan);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataLaporanActionPerformed

    private void Btn_DataLaporan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataLaporan1ActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataLaporan);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataLaporan1ActionPerformed

    private void Btn_DataPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataPemesanActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataPemesan);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataPemesanActionPerformed

    private void Btn_DataLaporan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataLaporan2ActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataLaporan);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataLaporan2ActionPerformed

    private void Btn_DataBarang2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataBarang2ActionPerformed
        
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataBarang);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
    }//GEN-LAST:event_Btn_DataBarang2ActionPerformed

    private void Btn_DataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataBarangActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataBarang);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataBarangActionPerformed

    private void Btn_DataBarang1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataBarang1ActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataBarang);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataBarang1ActionPerformed

    private void Btn_DataPemesan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataPemesan1ActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataPemesan);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataPemesan1ActionPerformed

    private void Btn_DataPemesan2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DataPemesan2ActionPerformed
        pn_konten_Beranda.removeAll();
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
        
        pn_konten_Beranda.add(Beranda_DataPemesan);
        pn_konten_Beranda.repaint();
        pn_konten_Beranda.revalidate();
    }//GEN-LAST:event_Btn_DataPemesan2ActionPerformed

    private void Btn_DataBarang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_DataBarang2MouseClicked
        
    }//GEN-LAST:event_Btn_DataBarang2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Beranda_DataBarang;
    private javax.swing.JPanel Beranda_DataLaporan;
    private javax.swing.JPanel Beranda_DataPemesan;
    private rojerusan.RSMaterialButtonRectangle Btn_DataBarang;
    private rojerusan.RSMaterialButtonRectangle Btn_DataBarang1;
    private rojerusan.RSMaterialButtonRectangle Btn_DataBarang2;
    private rojerusan.RSMaterialButtonRectangle Btn_DataLaporan;
    private rojerusan.RSMaterialButtonRectangle Btn_DataLaporan1;
    private rojerusan.RSMaterialButtonRectangle Btn_DataLaporan2;
    private rojerusan.RSMaterialButtonRectangle Btn_DataPemesan;
    private rojerusan.RSMaterialButtonRectangle Btn_DataPemesan1;
    private rojerusan.RSMaterialButtonRectangle Btn_DataPemesan2;
    private javax.swing.JLabel Jd_Beranda1;
    private javax.swing.JLabel Jd_Beranda2;
    private javax.swing.JLabel Jd_Beranda4;
    private javax.swing.JLabel Jd_DataBarang;
    private javax.swing.JLabel Jd_DataPemesan;
    private javax.swing.JLabel Jd_DataPemesan1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel pn_konten_Beranda;
    private javax.swing.JTable tb_b;
    private javax.swing.JTable tb_b2;
    private javax.swing.JTable tb_b3;
    // End of variables declaration//GEN-END:variables
}
