/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tesframe;

/**
 *
 * @author acer
 */
public class Laporan extends javax.swing.JPanel {

    /**
     * Creates new form Laporan
     */
    public Laporan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_konten_Laporan = new javax.swing.JPanel();
        Laporan_Barang = new javax.swing.JPanel();
        Jd_Laporan = new javax.swing.JLabel();
        pn_PilihLaporan = new javax.swing.JPanel();
        cbx_PilihJenisLaporan = new javax.swing.JComboBox<>();
        Btn_Kembali = new rojerusan.RSMaterialButtonRectangle();
        pn_Main = new javax.swing.JPanel();
        Lb_Main = new javax.swing.JLabel();
        pn_LaporanBarang = new javax.swing.JPanel();
        Lb_LaporanBarang = new javax.swing.JLabel();
        Btn_Print1 = new javax.swing.JButton();
        pn_LaporanPemesan = new javax.swing.JPanel();
        Lb_LaporanPemesan = new javax.swing.JLabel();
        Btn_Print2 = new javax.swing.JButton();
        pn_LaporanBarangMasuk = new javax.swing.JPanel();
        Lb_BarangMasuk = new javax.swing.JLabel();
        Btn_Print3 = new javax.swing.JButton();
        pn_LaporanBarangKeluar = new javax.swing.JPanel();
        Lb_BarangKeluar = new javax.swing.JLabel();
        Btn_Print4 = new javax.swing.JButton();
        pn_TampilLaporan = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.CardLayout());

        pn_konten_Laporan.setPreferredSize(new java.awt.Dimension(1024, 768));
        pn_konten_Laporan.setLayout(new java.awt.CardLayout());

        Laporan_Barang.setBackground(new java.awt.Color(204, 204, 204));
        Laporan_Barang.setPreferredSize(new java.awt.Dimension(1024, 768));

        Jd_Laporan.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Laporan.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Laporan.setText("Laporan");

        pn_PilihLaporan.setBackground(new java.awt.Color(255, 255, 255));
        pn_PilihLaporan.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbx_PilihJenisLaporan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Laporan", "Laporan Barang", "Laporan Pemesan", "Laporan Barang Masuk", "Laporan Barang Keluar" }));
        cbx_PilihJenisLaporan.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cbx_PilihJenisLaporanFocusGained(evt);
            }
        });
        cbx_PilihJenisLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cbx_PilihJenisLaporanMouseClicked(evt);
            }
        });
        cbx_PilihJenisLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_PilihJenisLaporanActionPerformed(evt);
            }
        });
        pn_PilihLaporan.add(cbx_PilihJenisLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 35, 191, 31));

        Btn_Kembali.setBackground(new java.awt.Color(204, 153, 0));
        Btn_Kembali.setText("Kembali");
        pn_PilihLaporan.add(Btn_Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 180, 48));

        pn_Main.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lb_Main.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_Main.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_Main.setText("Main");

        javax.swing.GroupLayout pn_MainLayout = new javax.swing.GroupLayout(pn_Main);
        pn_Main.setLayout(pn_MainLayout);
        pn_MainLayout.setHorizontalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_MainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_Main, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_MainLayout.setVerticalGroup(
            pn_MainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_MainLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(Lb_Main)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pn_PilihLaporan.add(pn_Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 191, -1));

        pn_LaporanBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lb_LaporanBarang.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_LaporanBarang.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_LaporanBarang.setText("Laporan Barang");

        Btn_Print1.setBackground(new java.awt.Color(51, 204, 0));
        Btn_Print1.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Btn_Print1.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Print1.setText("Print");
        Btn_Print1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Print1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_LaporanBarangLayout = new javax.swing.GroupLayout(pn_LaporanBarang);
        pn_LaporanBarang.setLayout(pn_LaporanBarangLayout);
        pn_LaporanBarangLayout.setHorizontalGroup(
            pn_LaporanBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_LaporanBarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanBarangLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(Btn_Print1)
                .addGap(65, 65, 65))
        );
        pn_LaporanBarangLayout.setVerticalGroup(
            pn_LaporanBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LaporanBarangLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Lb_LaporanBarang)
                .addGap(33, 33, 33)
                .addComponent(Btn_Print1)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pn_PilihLaporan.add(pn_LaporanBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 191, -1));

        pn_LaporanPemesan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lb_LaporanPemesan.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_LaporanPemesan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_LaporanPemesan.setText("Laporan Pemesan");

        Btn_Print2.setBackground(new java.awt.Color(51, 204, 0));
        Btn_Print2.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Btn_Print2.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Print2.setText("Print");

        javax.swing.GroupLayout pn_LaporanPemesanLayout = new javax.swing.GroupLayout(pn_LaporanPemesan);
        pn_LaporanPemesan.setLayout(pn_LaporanPemesanLayout);
        pn_LaporanPemesanLayout.setHorizontalGroup(
            pn_LaporanPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanPemesanLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_LaporanPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanPemesanLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(Btn_Print2)
                .addGap(65, 65, 65))
        );
        pn_LaporanPemesanLayout.setVerticalGroup(
            pn_LaporanPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LaporanPemesanLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Lb_LaporanPemesan)
                .addGap(33, 33, 33)
                .addComponent(Btn_Print2)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pn_PilihLaporan.add(pn_LaporanPemesan, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 191, -1));

        pn_LaporanBarangMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lb_BarangMasuk.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_BarangMasuk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_BarangMasuk.setText("Laporan Barang Masuk");

        Btn_Print3.setBackground(new java.awt.Color(51, 204, 0));
        Btn_Print3.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Btn_Print3.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Print3.setText("Print");

        javax.swing.GroupLayout pn_LaporanBarangMasukLayout = new javax.swing.GroupLayout(pn_LaporanBarangMasuk);
        pn_LaporanBarangMasuk.setLayout(pn_LaporanBarangMasukLayout);
        pn_LaporanBarangMasukLayout.setHorizontalGroup(
            pn_LaporanBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanBarangMasukLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_BarangMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanBarangMasukLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(Btn_Print3)
                .addGap(65, 65, 65))
        );
        pn_LaporanBarangMasukLayout.setVerticalGroup(
            pn_LaporanBarangMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LaporanBarangMasukLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Lb_BarangMasuk)
                .addGap(33, 33, 33)
                .addComponent(Btn_Print3)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pn_PilihLaporan.add(pn_LaporanBarangMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 191, -1));

        pn_LaporanBarangKeluar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Lb_BarangKeluar.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Lb_BarangKeluar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Lb_BarangKeluar.setText("Laporan Barang Keluar");

        Btn_Print4.setBackground(new java.awt.Color(51, 204, 0));
        Btn_Print4.setFont(new java.awt.Font("SansSerif", 1, 12)); // NOI18N
        Btn_Print4.setForeground(new java.awt.Color(255, 255, 255));
        Btn_Print4.setText("Print");

        javax.swing.GroupLayout pn_LaporanBarangKeluarLayout = new javax.swing.GroupLayout(pn_LaporanBarangKeluar);
        pn_LaporanBarangKeluar.setLayout(pn_LaporanBarangKeluarLayout);
        pn_LaporanBarangKeluarLayout.setHorizontalGroup(
            pn_LaporanBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanBarangKeluarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Lb_BarangKeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_LaporanBarangKeluarLayout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addComponent(Btn_Print4)
                .addGap(65, 65, 65))
        );
        pn_LaporanBarangKeluarLayout.setVerticalGroup(
            pn_LaporanBarangKeluarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LaporanBarangKeluarLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(Lb_BarangKeluar)
                .addGap(33, 33, 33)
                .addComponent(Btn_Print4)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pn_PilihLaporan.add(pn_LaporanBarangKeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 95, 191, -1));

        pn_TampilLaporan.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pn_TampilLaporanLayout = new javax.swing.GroupLayout(pn_TampilLaporan);
        pn_TampilLaporan.setLayout(pn_TampilLaporanLayout);
        pn_TampilLaporanLayout.setHorizontalGroup(
            pn_TampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 775, Short.MAX_VALUE)
        );
        pn_TampilLaporanLayout.setVerticalGroup(
            pn_TampilLaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 671, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout Laporan_BarangLayout = new javax.swing.GroupLayout(Laporan_Barang);
        Laporan_Barang.setLayout(Laporan_BarangLayout);
        Laporan_BarangLayout.setHorizontalGroup(
            Laporan_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Laporan_BarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pn_PilihLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_TampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(Laporan_BarangLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(Jd_Laporan)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Laporan_BarangLayout.setVerticalGroup(
            Laporan_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Laporan_BarangLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Jd_Laporan)
                .addGap(25, 25, 25)
                .addGroup(Laporan_BarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_TampilLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pn_PilihLaporan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pn_konten_Laporan.add(Laporan_Barang, "card2");

        add(pn_konten_Laporan, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_PilihJenisLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_PilihJenisLaporanActionPerformed
        if (cbx_PilihJenisLaporan.getSelectedItem()=="Pilih Jenis Laporan"){
           pn_Main.setVisible(true);
           pn_LaporanBarang.setVisible(false);
           pn_LaporanPemesan.setVisible(false);
           pn_LaporanBarangMasuk.setVisible(false);
           pn_LaporanBarangKeluar.setVisible(false);
        }else if (cbx_PilihJenisLaporan.getSelectedItem()=="Laporan Barang"){
           pn_Main.setVisible(false);
           pn_LaporanBarang.setVisible(true);
           pn_LaporanPemesan.setVisible(false);
           pn_LaporanBarangMasuk.setVisible(false);
           pn_LaporanBarangKeluar.setVisible(false);
        }else if (cbx_PilihJenisLaporan.getSelectedItem()=="Laporan Pemesan"){
           pn_Main.setVisible(false);
           pn_LaporanBarang.setVisible(false);
           pn_LaporanPemesan.setVisible(true);
           pn_LaporanBarangMasuk.setVisible(false);
           pn_LaporanBarangKeluar.setVisible(false);
        }
        else if (cbx_PilihJenisLaporan.getSelectedItem()=="Laporan Barang Masuk"){
           pn_Main.setVisible(false);
           pn_LaporanBarang.setVisible(false);
           pn_LaporanPemesan.setVisible(false);
           pn_LaporanBarangMasuk.setVisible(true);
           pn_LaporanBarangKeluar.setVisible(false);
        }
        else if (cbx_PilihJenisLaporan.getSelectedItem()=="Laporan Barang Keluar"){
           pn_Main.setVisible(false);
           pn_LaporanBarang.setVisible(false);
           pn_LaporanPemesan.setVisible(false);
           pn_LaporanBarangMasuk.setVisible(false);
           pn_LaporanBarangKeluar.setVisible(true);
        }
    }//GEN-LAST:event_cbx_PilihJenisLaporanActionPerformed

    private void cbx_PilihJenisLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cbx_PilihJenisLaporanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_PilihJenisLaporanMouseClicked

    private void cbx_PilihJenisLaporanFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cbx_PilihJenisLaporanFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_PilihJenisLaporanFocusGained

    private void Btn_Print1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Print1ActionPerformed
        pn_TampilLaporan.removeAll();
        
    }//GEN-LAST:event_Btn_Print1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Btn_Kembali;
    private javax.swing.JButton Btn_Print1;
    private javax.swing.JButton Btn_Print2;
    private javax.swing.JButton Btn_Print3;
    private javax.swing.JButton Btn_Print4;
    private javax.swing.JLabel Jd_Laporan;
    private javax.swing.JPanel Laporan_Barang;
    private javax.swing.JLabel Lb_BarangKeluar;
    private javax.swing.JLabel Lb_BarangMasuk;
    private javax.swing.JLabel Lb_LaporanBarang;
    private javax.swing.JLabel Lb_LaporanPemesan;
    private javax.swing.JLabel Lb_Main;
    private javax.swing.JComboBox<String> cbx_PilihJenisLaporan;
    private javax.swing.JPanel pn_LaporanBarang;
    private javax.swing.JPanel pn_LaporanBarangKeluar;
    private javax.swing.JPanel pn_LaporanBarangMasuk;
    private javax.swing.JPanel pn_LaporanPemesan;
    private javax.swing.JPanel pn_Main;
    private javax.swing.JPanel pn_PilihLaporan;
    private javax.swing.JPanel pn_TampilLaporan;
    private javax.swing.JPanel pn_konten_Laporan;
    // End of variables declaration//GEN-END:variables
}
