/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package tesframe;

import java.io.File;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

import static sun.jvm.hotspot.HelloWorld.e;
import static tesframe.koneksi.getConnection;

/**
 *
 * @author acer
 */
public class Pemesan extends javax.swing.JPanel {
    koneksi db = new koneksi();
    DefaultTableModel model = new DefaultTableModel();

    /**
     * Creates new form Pemesan
     */
    public Pemesan() {
        initComponents();
        ResultSet hasil = db.ambilData("SELECT * FROM barang ");
        try {
            while (hasil.next()){
                nb.addItem(hasil.getString("nama_barang"));
                d_nb.addItem(hasil.getString("nama_barang"));
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Pemesan.class.getName()).log(Level.SEVERE, null, ex);
        }
        aturColumnn();
        aturBariss();
    }
    public void aturColumnn(){
        
        model.addColumn("ID");
        model.addColumn("Nama Pemesan");
        model.addColumn("Nama Barang");
        model.addColumn("Jumlah Pesanan");
        model.addColumn("Tanggal Pesanan");
        model.addColumn("Alamat");
        model.addColumn("No Telepon");
        model.addColumn("Harga");
        model.addColumn("Status");
        tb_p1.setModel(model);
    }
    public void aturBariss(){
        ResultSet hasil = db.ambilData("SELECT * FROM pemesan");
        
        try {
            while(hasil.next()) {
                model.addRow(new Object[]{hasil.getString("idpemesan"), hasil.getString("nama_pemesan"),hasil.getString("nama_barang"),hasil.getString("jumlah_barang"),hasil.getString("tgl"), hasil.getString("alamat"), hasil.getString("no_tlp"),hasil.getString("harga"),hasil.getString("Status")});
                
            }
             tb_p1.setModel(model);
             
             tb_rp1.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_konten_pemesan = new javax.swing.JPanel();
        Pemesan_RincianPemesan = new javax.swing.JPanel();
        Jd_Pemesan = new javax.swing.JLabel();
        Lb_RincianPesanan = new javax.swing.JLabel();
        Btn_BuatPesanan = new rojerusan.RSMaterialButtonRectangle();
        Btn_ProsesPesanan = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_rp1 = new javax.swing.JTable();
        Btn_HapusPemesan = new rojerusan.RSMaterialButtonRectangle();
        Btn_Cetak = new rojerusan.RSMaterialButtonRectangle();
        Btn_RicianPesanan = new rojerusan.RSMaterialButtonRectangle();
        Jd_Pemesan6 = new javax.swing.JLabel();
        Jd_Pemesan7 = new javax.swing.JLabel();
        Pemesan_BuatPesanan = new javax.swing.JPanel();
        Jd_Pemesan1 = new javax.swing.JLabel();
        Btn_BuatPesanan_Siimpan = new rojerusan.RSMaterialButtonRectangle();
        Lb_Tgl = new javax.swing.JLabel();
        tp = new javax.swing.JTextField();
        Lb_Nama = new javax.swing.JLabel();
        np = new javax.swing.JTextField();
        Lb_Alamat = new javax.swing.JLabel();
        Lb_NoTelp = new javax.swing.JLabel();
        nt = new javax.swing.JTextField();
        Lb_IdBarang = new javax.swing.JLabel();
        ib = new javax.swing.JTextField();
        Lb_NamaBarang = new javax.swing.JLabel();
        Lb_Jumlah = new javax.swing.JLabel();
        jb = new javax.swing.JTextField();
        Lb_Harga = new javax.swing.JLabel();
        ht = new javax.swing.JTextField();
        Btn_BuatPesanan_Batal = new rojerusan.RSMaterialButtonRectangle();
        alm = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Jd_BuatPesanan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sts = new javax.swing.JComboBox<>();
        nb = new javax.swing.JComboBox<>();
        Btn_BuatPesanan_Tambah = new rojerusan.RSMaterialButtonRectangle();
        Pemesan_ProsesPesanan = new javax.swing.JPanel();
        Jd_Pemesan2 = new javax.swing.JLabel();
        Btn_ProsesPesanan_Batalkan = new rojerusan.RSMaterialButtonRectangle();
        Btn_ProsesPesanan_Kembali = new rojerusan.RSMaterialButtonRectangle();
        jLabel4 = new javax.swing.JLabel();
        Jd_ProsesPesanan = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Btn_ProsesPesanan_Selesaikan = new rojerusan.RSMaterialButtonRectangle();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_p1 = new javax.swing.JTable();
        Btn_ProsesPesanan_Detail = new rojerusan.RSMaterialButtonRectangle();
        Pemesan_ProsesPesanan_Detail = new javax.swing.JPanel();
        Jd_Pemesan4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Jd_ProsesPesanan1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        d_idp = new javax.swing.JTextField();
        d_nama = new javax.swing.JTextField();
        d_jp = new javax.swing.JTextField();
        d_tg = new javax.swing.JTextField();
        d_alm = new javax.swing.JTextField();
        d_nt = new javax.swing.JTextField();
        d_harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        rSMaterialButtonRectangle1 = new rojerusan.RSMaterialButtonRectangle();
        d_nb = new javax.swing.JComboBox<>();
        d_sts = new javax.swing.JComboBox<>();
        Btn_DetailKembali = new rojerusan.RSMaterialButtonRectangle();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1024, 768));
        setLayout(new java.awt.CardLayout());

        pn_konten_pemesan.setBackground(new java.awt.Color(255, 255, 255));
        pn_konten_pemesan.setPreferredSize(new java.awt.Dimension(1024, 768));
        pn_konten_pemesan.setLayout(new java.awt.CardLayout());

        Pemesan_RincianPemesan.setBackground(new java.awt.Color(255, 255, 255));
        Pemesan_RincianPemesan.setPreferredSize(new java.awt.Dimension(1024, 768));

        Jd_Pemesan.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Pemesan.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Pemesan.setText("Pemesan");

        Lb_RincianPesanan.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_RincianPesanan.setText("Rincian Pesanan");

        Btn_BuatPesanan.setText("Buat Pesanan");
        Btn_BuatPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuatPesananActionPerformed(evt);
            }
        });

        Btn_ProsesPesanan.setText("proses pesanan");
        Btn_ProsesPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProsesPesananActionPerformed(evt);
            }
        });

        tb_rp1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tb_rp1);

        Btn_HapusPemesan.setBackground(new java.awt.Color(255, 51, 0));
        Btn_HapusPemesan.setText("HAPUS");
        Btn_HapusPemesan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_HapusPemesanActionPerformed(evt);
            }
        });

        Btn_Cetak.setBackground(new java.awt.Color(0, 204, 51));
        Btn_Cetak.setText("Cetak Nota");
        Btn_Cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_CetakActionPerformed(evt);
            }
        });

        Btn_RicianPesanan.setText("Rincian Pesanan");
        Btn_RicianPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_RicianPesananActionPerformed(evt);
            }
        });

        Jd_Pemesan6.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Pemesan6.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Pemesan6.setText(">");

        Jd_Pemesan7.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Pemesan7.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Pemesan7.setText("Rincian Pesanan");

        javax.swing.GroupLayout Pemesan_RincianPemesanLayout = new javax.swing.GroupLayout(Pemesan_RincianPemesan);
        Pemesan_RincianPemesan.setLayout(Pemesan_RincianPemesanLayout);
        Pemesan_RincianPemesanLayout.setHorizontalGroup(
            Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                        .addComponent(Lb_RincianPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pemesan_RincianPemesanLayout.createSequentialGroup()
                        .addGroup(Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                                .addComponent(Btn_HapusPemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(64, 64, 64)
                                .addComponent(Btn_Cetak, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane3))
                        .addGap(92, 92, 92))
                    .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                        .addGroup(Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                                .addComponent(Btn_BuatPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(Btn_ProsesPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(60, 60, 60)
                                .addComponent(Btn_RicianPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                                .addComponent(Jd_Pemesan, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Jd_Pemesan6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Jd_Pemesan7, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(374, Short.MAX_VALUE))))
        );
        Pemesan_RincianPemesanLayout.setVerticalGroup(
            Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_RincianPemesanLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Pemesan, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(Jd_Pemesan6, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(Jd_Pemesan7, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE))
                .addGap(43, 43, 43)
                .addGroup(Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_BuatPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(Btn_ProsesPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                    .addComponent(Btn_RicianPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addGap(62, 62, 62)
                .addComponent(Lb_RincianPesanan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(Pemesan_RincianPemesanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_HapusPemesan, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(Btn_Cetak, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                .addGap(56, 56, 56))
        );

        pn_konten_pemesan.add(Pemesan_RincianPemesan, "card2");

        Pemesan_BuatPesanan.setBackground(new java.awt.Color(255, 255, 255));
        Pemesan_BuatPesanan.setPreferredSize(new java.awt.Dimension(1024, 768));

        Jd_Pemesan1.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Pemesan1.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Pemesan1.setText("Pemesan");

        Btn_BuatPesanan_Siimpan.setText("Simpan");
        Btn_BuatPesanan_Siimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuatPesanan_SiimpanActionPerformed(evt);
            }
        });

        Lb_Tgl.setBackground(new java.awt.Color(255, 255, 255));
        Lb_Tgl.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Tgl.setText("Tanggal Pesanan");

        tp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpActionPerformed(evt);
            }
        });

        Lb_Nama.setBackground(new java.awt.Color(255, 255, 255));
        Lb_Nama.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Nama.setText("Nama Pemesan");

        Lb_Alamat.setBackground(new java.awt.Color(255, 255, 255));
        Lb_Alamat.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Alamat.setText("Alamat");

        Lb_NoTelp.setBackground(new java.awt.Color(255, 255, 255));
        Lb_NoTelp.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_NoTelp.setText("No Telepon");

        Lb_IdBarang.setBackground(new java.awt.Color(255, 255, 255));
        Lb_IdBarang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_IdBarang.setText("ID Pesanan");

        ib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ibActionPerformed(evt);
            }
        });

        Lb_NamaBarang.setBackground(new java.awt.Color(255, 255, 255));
        Lb_NamaBarang.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_NamaBarang.setText("Nama Barang");

        Lb_Jumlah.setBackground(new java.awt.Color(255, 255, 255));
        Lb_Jumlah.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Jumlah.setText("Jumlah Barang");

        Lb_Harga.setBackground(new java.awt.Color(255, 255, 255));
        Lb_Harga.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        Lb_Harga.setText("Harga Total");

        Btn_BuatPesanan_Batal.setBackground(new java.awt.Color(204, 51, 0));
        Btn_BuatPesanan_Batal.setText("Batal");
        Btn_BuatPesanan_Batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuatPesanan_BatalActionPerformed(evt);
            }
        });

        alm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                almActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel2.setText(">");

        Jd_BuatPesanan.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_BuatPesanan.setForeground(new java.awt.Color(0, 31, 63));
        Jd_BuatPesanan.setText("Buat Pesanan");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel3.setText("Status");

        sts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status", "Selesai", "Menunggu", " " }));

        nb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang" }));

        Btn_BuatPesanan_Tambah.setBackground(new java.awt.Color(0, 255, 51));
        Btn_BuatPesanan_Tambah.setText("TAMBAH");
        Btn_BuatPesanan_Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BuatPesanan_TambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pemesan_BuatPesananLayout = new javax.swing.GroupLayout(Pemesan_BuatPesanan);
        Pemesan_BuatPesanan.setLayout(Pemesan_BuatPesananLayout);
        Pemesan_BuatPesananLayout.setHorizontalGroup(
            Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addComponent(Lb_Alamat)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Jd_Pemesan1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2))
                            .addComponent(Btn_BuatPesanan_Siimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jd_BuatPesanan)
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Btn_BuatPesanan_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(Btn_BuatPesanan_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(alm, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_Nama)
                                    .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Tgl)
                                    .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Lb_IdBarang)
                                    .addComponent(ib)
                                    .addComponent(Lb_NamaBarang)
                                    .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_Harga)
                                    .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lb_Jumlah)
                                    .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Lb_NoTelp)
                                    .addComponent(nt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(80, 80, 80)
                                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(sts, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(124, 124, 124))))
        );
        Pemesan_BuatPesananLayout.setVerticalGroup(
            Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Pemesan1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(Jd_BuatPesanan))
                .addGap(30, 30, 30)
                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_BuatPesanan_Siimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_BuatPesanan_Batal, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_BuatPesanan_Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addComponent(Lb_NamaBarang)
                        .addGap(96, 96, 96))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Lb_Tgl)
                                .addGap(10, 10, 10)
                                .addComponent(tp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Lb_IdBarang)
                                .addGap(10, 10, 10)
                                .addComponent(ib, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Lb_Jumlah)
                                .addGap(10, 10, 10)
                                .addComponent(jb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(35, 35, 35)
                        .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Lb_Nama)
                                .addGap(10, 10, 10)
                                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(np, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                                .addComponent(Lb_Harga)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ht, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(Lb_Alamat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(alm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(Pemesan_BuatPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addComponent(Lb_NoTelp)
                        .addGap(10, 10, 10)
                        .addComponent(nt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pemesan_BuatPesananLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(271, 271, 271))
        );

        pn_konten_pemesan.add(Pemesan_BuatPesanan, "card2");

        Pemesan_ProsesPesanan.setBackground(new java.awt.Color(255, 255, 255));
        Pemesan_ProsesPesanan.setPreferredSize(new java.awt.Dimension(1024, 768));

        Jd_Pemesan2.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Pemesan2.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Pemesan2.setText("Pemesan");

        Btn_ProsesPesanan_Batalkan.setBackground(new java.awt.Color(255, 51, 0));
        Btn_ProsesPesanan_Batalkan.setText("Batalkan");
        Btn_ProsesPesanan_Batalkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProsesPesanan_BatalkanActionPerformed(evt);
            }
        });

        Btn_ProsesPesanan_Kembali.setBackground(new java.awt.Color(255, 153, 51));
        Btn_ProsesPesanan_Kembali.setText("Kembali");
        Btn_ProsesPesanan_Kembali.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Btn_ProsesPesanan_KembaliStateChanged(evt);
            }
        });
        Btn_ProsesPesanan_Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProsesPesanan_KembaliActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel4.setText(">");

        Jd_ProsesPesanan.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_ProsesPesanan.setForeground(new java.awt.Color(0, 31, 63));
        Jd_ProsesPesanan.setText("Proses Pesanan");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Daftar Pesanan");

        Btn_ProsesPesanan_Selesaikan.setText("Selesaikan");
        Btn_ProsesPesanan_Selesaikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProsesPesanan_SelesaikanActionPerformed(evt);
            }
        });

        tb_p1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tb_p1);
        if (tb_p1.getColumnModel().getColumnCount() > 0) {
            tb_p1.getColumnModel().getColumn(0).setMinWidth(50);
            tb_p1.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        Btn_ProsesPesanan_Detail.setBackground(new java.awt.Color(0, 153, 255));
        Btn_ProsesPesanan_Detail.setText("Detail");
        Btn_ProsesPesanan_Detail.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                Btn_ProsesPesanan_DetailStateChanged(evt);
            }
        });
        Btn_ProsesPesanan_Detail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Btn_ProsesPesanan_DetailMouseClicked(evt);
            }
        });
        Btn_ProsesPesanan_Detail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ProsesPesanan_DetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pemesan_ProsesPesananLayout = new javax.swing.GroupLayout(Pemesan_ProsesPesanan);
        Pemesan_ProsesPesanan.setLayout(Pemesan_ProsesPesananLayout);
        Pemesan_ProsesPesananLayout.setHorizontalGroup(
            Pemesan_ProsesPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_ProsesPesananLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Pemesan_ProsesPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .addGroup(Pemesan_ProsesPesananLayout.createSequentialGroup()
                        .addComponent(Jd_Pemesan2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(Jd_ProsesPesanan))
                    .addGroup(Pemesan_ProsesPesananLayout.createSequentialGroup()
                        .addComponent(Btn_ProsesPesanan_Selesaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(Btn_ProsesPesanan_Batalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(Btn_ProsesPesanan_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(Btn_ProsesPesanan_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        Pemesan_ProsesPesananLayout.setVerticalGroup(
            Pemesan_ProsesPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_ProsesPesananLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Pemesan_ProsesPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Pemesan2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(Jd_ProsesPesanan))
                .addGap(35, 35, 35)
                .addGroup(Pemesan_ProsesPesananLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_ProsesPesanan_Batalkan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ProsesPesanan_Kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ProsesPesanan_Detail, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_ProsesPesanan_Selesaikan, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                .addGap(150, 150, 150))
        );

        pn_konten_pemesan.add(Pemesan_ProsesPesanan, "card2");

        Pemesan_ProsesPesanan_Detail.setBackground(new java.awt.Color(255, 255, 255));
        Pemesan_ProsesPesanan_Detail.setPreferredSize(new java.awt.Dimension(1024, 768));

        Jd_Pemesan4.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        Jd_Pemesan4.setForeground(new java.awt.Color(0, 31, 63));
        Jd_Pemesan4.setText("Pemesan");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel5.setText(">");

        Jd_ProsesPesanan1.setFont(new java.awt.Font("SansSerif", 1, 26)); // NOI18N
        Jd_ProsesPesanan1.setForeground(new java.awt.Color(0, 31, 63));
        Jd_ProsesPesanan1.setText("Detail Pesanan");

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel6.setText("Daftar Pesanan");

        d_idp.setEnabled(false);

        jLabel7.setText("ID Pemesan");

        jLabel8.setText("Nama");

        jLabel9.setText("Nama Barang");

        jLabel10.setText("Jumlah Pesanan");

        jLabel11.setText("Tanggal Pesanan");

        jLabel12.setText("Alamat");

        jLabel13.setText("No Telepon");

        jLabel14.setText("Harga");

        jLabel15.setText("Status");

        rSMaterialButtonRectangle1.setBackground(new java.awt.Color(0, 255, 51));
        rSMaterialButtonRectangle1.setText("SIMPAN");
        rSMaterialButtonRectangle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSMaterialButtonRectangle1ActionPerformed(evt);
            }
        });

        d_nb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Barang" }));

        d_sts.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Status", "Selesai", "Menunggu" }));

        Btn_DetailKembali.setBackground(new java.awt.Color(255, 204, 0));
        Btn_DetailKembali.setText("Kembali");
        Btn_DetailKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DetailKembaliActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Pemesan_ProsesPesanan_DetailLayout = new javax.swing.GroupLayout(Pemesan_ProsesPesanan_Detail);
        Pemesan_ProsesPesanan_Detail.setLayout(Pemesan_ProsesPesanan_DetailLayout);
        Pemesan_ProsesPesanan_DetailLayout.setHorizontalGroup(
            Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                        .addComponent(Jd_Pemesan4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(Jd_ProsesPesanan1))
                    .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                        .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(d_nb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(d_nt, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d_alm, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d_tg, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d_jp, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(d_nama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                                        .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(d_idp, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addGap(425, 425, 425)))
                                .addComponent(jLabel8)
                                .addComponent(jLabel13)))
                        .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14)
                                    .addComponent(d_harga)
                                    .addComponent(d_sts, 0, 187, Short.MAX_VALUE)))
                            .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Btn_DetailKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(50, 50, 50))
        );
        Pemesan_ProsesPesanan_DetailLayout.setVerticalGroup(
            Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Jd_Pemesan4, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Jd_ProsesPesanan1))
                .addGap(45, 45, 45)
                .addComponent(jLabel6)
                .addGap(38, 38, 38)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_idp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_harga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15))
                .addGap(2, 2, 2)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(d_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_sts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Pemesan_ProsesPesanan_DetailLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_nb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_jp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_tg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(d_alm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addGap(4, 4, 4)
                        .addComponent(d_nt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Pemesan_ProsesPesanan_DetailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rSMaterialButtonRectangle1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Btn_DetailKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );

        pn_konten_pemesan.add(Pemesan_ProsesPesanan_Detail, "card2");

        add(pn_konten_pemesan, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_BuatPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuatPesananActionPerformed
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_BuatPesanan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_BuatPesananActionPerformed

    private void Btn_BuatPesanan_BatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuatPesanan_BatalActionPerformed
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_RincianPemesan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_BuatPesanan_BatalActionPerformed

    private void Btn_ProsesPesanan_KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_KembaliActionPerformed
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_RincianPemesan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_ProsesPesanan_KembaliActionPerformed

    private void Btn_ProsesPesanan_KembaliStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_KembaliStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_ProsesPesanan_KembaliStateChanged

    private void Btn_ProsesPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProsesPesananActionPerformed
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_ProsesPesanan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_ProsesPesananActionPerformed

    private void tpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpActionPerformed

    private void ibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ibActionPerformed

    private void almActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_almActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_almActionPerformed

    private void Btn_BuatPesanan_SiimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuatPesanan_SiimpanActionPerformed
        String id = ib.getText();
        String nama_b = String.valueOf(nb.getSelectedItem());
        String nama_p = np.getText();
        String jumlah_b = jb.getText();
        String tanggal = tp.getText();
        String alamat = alm.getText();
        String no = nt.getText();
        String harga = ht.getText();
        String status = String.valueOf(sts.getSelectedItem());
        
        db.aksi("INSERT INTO pemesan VALUES ('" + id + "','" + nama_p + "','"+jumlah_b+"','"+tanggal+"','"+alamat+"','"+no+"','"+harga+"','"+status+"','"+nama_b+"')");
         model.setRowCount(0);
         tb_p1.setModel(model);
         aturBariss();
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_RincianPemesan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_BuatPesanan_SiimpanActionPerformed

    private void Btn_ProsesPesanan_SelesaikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_SelesaikanActionPerformed
        int Row = tb_p1.getSelectedRow();
    String ID = (String) tb_p1.getValueAt(Row, 0);
    db.aksi("UPDATE pemesan SET Status = 'SELESAI' WHERE idPemesan ='"+ID+"'");
    model.setRowCount(0);
    tb_p1.setModel(model);
    aturBariss();
    }//GEN-LAST:event_Btn_ProsesPesanan_SelesaikanActionPerformed

    private void Btn_ProsesPesanan_BatalkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_BatalkanActionPerformed
        int Row = tb_p1.getSelectedRow();
    String ID = (String) tb_p1.getValueAt(Row, 0);
    db.aksi("UPDATE pemesan SET Status = 'BATAL' WHERE idPemesan ='"+ID+"'");
    model.setRowCount(0);
    tb_p1.setModel(model);
    aturBariss();
    }//GEN-LAST:event_Btn_ProsesPesanan_BatalkanActionPerformed

    private void Btn_ProsesPesanan_DetailStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_DetailStateChanged
        
    }//GEN-LAST:event_Btn_ProsesPesanan_DetailStateChanged

    private void Btn_ProsesPesanan_DetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_DetailActionPerformed
        int selectedRow = tb_p1.getSelectedRow();
        
        d_idp.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 0)));
        d_nama.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 1)));
        d_nb.setSelectedItem(String.valueOf(tb_p1.getValueAt(selectedRow, 2)));
        d_jp.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 3)));
        d_tg.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 4)));
        d_alm.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 5)));
        d_nt.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 6)));
        d_harga.setText(String.valueOf(tb_p1.getValueAt(selectedRow, 7)));
        d_sts.setSelectedItem(String.valueOf(tb_p1.getValueAt(selectedRow, 8)));
        
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_ProsesPesanan_Detail);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_ProsesPesanan_DetailActionPerformed

    private void Btn_ProsesPesanan_DetailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Btn_ProsesPesanan_DetailMouseClicked
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_ProsesPesanan_Detail);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_ProsesPesanan_DetailMouseClicked

    private void rSMaterialButtonRectangle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rSMaterialButtonRectangle1ActionPerformed
        int Row = tb_p1.getSelectedRow();
        String ID = (String) tb_p1.getValueAt(Row, 0);
        db.aksi("UPDATE pemesan SET nama_pemesan = '"+d_nama.getText()+"',nama_barang = '"+d_nb.getSelectedItem()+"',jumlah_barang = '"+d_jp.getText()+"',tgl = '"+d_tg.getText()+"',alamat = '"+d_alm.getText()+"',no_tlp = '"+d_nt.getText()+"',harga = '"+d_harga.getText()+"',Status = '"+d_sts.getSelectedItem()+"' WHERE idpemesan = '"+d_idp.getText()+"'");
        model.setRowCount(0);
        tb_p1.setModel(model);
        aturBariss();
    
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_ProsesPesanan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_rSMaterialButtonRectangle1ActionPerformed

    private void Btn_BuatPesanan_TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BuatPesanan_TambahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_BuatPesanan_TambahActionPerformed

    private void Btn_HapusPemesanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_HapusPemesanActionPerformed
        int Row = tb_rp1.getSelectedRow();
    String ID = (String) tb_rp1.getValueAt(Row, 0);
    db.aksi("DELETE FROM pemesan WHERE idpemesan='"+ID+"'");
    model.setRowCount(0);
    tb_rp1.setModel(model);
    aturBariss();
    }//GEN-LAST:event_Btn_HapusPemesanActionPerformed

    private void Btn_CetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_CetakActionPerformed
         int Row = tb_rp1.getSelectedRow();
         
         if (Row != 0) {
            Object idpemesanValue = tb_rp1.getValueAt(Row, tb_rp1.getColumnModel().getColumnIndex("Idpemesan"));
            TableColumn column = tb_rp1.getColumn("idpemesan");
            if (column != null) {
            generateReport((String) idpemesanValue);
            }else{
            JOptionPane.showMessageDialog(this, "ID_Nota null untuk baris terpilih", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else {
             JOptionPane.showMessageDialog(this, "Tidak ada baris terpilih", "Error", JOptionPane.ERROR_MESSAGE);
         }
    }//GEN-LAST:event_Btn_CetakActionPerformed

    private void Btn_RicianPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_RicianPesananActionPerformed
       pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_RincianPemesan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_RicianPesananActionPerformed

    private void Btn_DetailKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DetailKembaliActionPerformed
        pn_konten_pemesan.removeAll();
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
        
        pn_konten_pemesan.add(Pemesan_ProsesPesanan);
        pn_konten_pemesan.repaint();
        pn_konten_pemesan.revalidate();
    }//GEN-LAST:event_Btn_DetailKembaliActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojerusan.RSMaterialButtonRectangle Btn_BuatPesanan;
    private rojerusan.RSMaterialButtonRectangle Btn_BuatPesanan_Batal;
    private rojerusan.RSMaterialButtonRectangle Btn_BuatPesanan_Siimpan;
    private rojerusan.RSMaterialButtonRectangle Btn_BuatPesanan_Tambah;
    private rojerusan.RSMaterialButtonRectangle Btn_Cetak;
    private rojerusan.RSMaterialButtonRectangle Btn_DetailKembali;
    private rojerusan.RSMaterialButtonRectangle Btn_HapusPemesan;
    private rojerusan.RSMaterialButtonRectangle Btn_ProsesPesanan;
    private rojerusan.RSMaterialButtonRectangle Btn_ProsesPesanan_Batalkan;
    private rojerusan.RSMaterialButtonRectangle Btn_ProsesPesanan_Detail;
    private rojerusan.RSMaterialButtonRectangle Btn_ProsesPesanan_Kembali;
    private rojerusan.RSMaterialButtonRectangle Btn_ProsesPesanan_Selesaikan;
    private rojerusan.RSMaterialButtonRectangle Btn_RicianPesanan;
    private javax.swing.JLabel Jd_BuatPesanan;
    private javax.swing.JLabel Jd_Pemesan;
    private javax.swing.JLabel Jd_Pemesan1;
    private javax.swing.JLabel Jd_Pemesan2;
    private javax.swing.JLabel Jd_Pemesan4;
    private javax.swing.JLabel Jd_Pemesan6;
    private javax.swing.JLabel Jd_Pemesan7;
    private javax.swing.JLabel Jd_ProsesPesanan;
    private javax.swing.JLabel Jd_ProsesPesanan1;
    private javax.swing.JLabel Lb_Alamat;
    private javax.swing.JLabel Lb_Harga;
    private javax.swing.JLabel Lb_IdBarang;
    private javax.swing.JLabel Lb_Jumlah;
    private javax.swing.JLabel Lb_Nama;
    private javax.swing.JLabel Lb_NamaBarang;
    private javax.swing.JLabel Lb_NoTelp;
    private javax.swing.JLabel Lb_RincianPesanan;
    private javax.swing.JLabel Lb_Tgl;
    private javax.swing.JPanel Pemesan_BuatPesanan;
    private javax.swing.JPanel Pemesan_ProsesPesanan;
    private javax.swing.JPanel Pemesan_ProsesPesanan_Detail;
    private javax.swing.JPanel Pemesan_RincianPemesan;
    private javax.swing.JTextField alm;
    private javax.swing.JTextField d_alm;
    private javax.swing.JTextField d_harga;
    private javax.swing.JTextField d_idp;
    private javax.swing.JTextField d_jp;
    private javax.swing.JTextField d_nama;
    private javax.swing.JComboBox<String> d_nb;
    private javax.swing.JTextField d_nt;
    private javax.swing.JComboBox<String> d_sts;
    private javax.swing.JTextField d_tg;
    private javax.swing.JTextField ht;
    private javax.swing.JTextField ib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jb;
    private javax.swing.JComboBox<String> nb;
    private javax.swing.JTextField np;
    private javax.swing.JTextField nt;
    private javax.swing.JPanel pn_konten_pemesan;
    private rojerusan.RSMaterialButtonRectangle rSMaterialButtonRectangle1;
    private javax.swing.JComboBox<String> sts;
    private javax.swing.JTable tb_p1;
    private javax.swing.JTable tb_rp1;
    private javax.swing.JTextField tp;
    // End of variables declaration//GEN-END:variables

    private void generateReport(String idpemesan) {
        try{
            InputStream reportStream = getClass().getResourceAsStream("/report/reportNota.jasper");
            JasperReport jasperReport = (JasperReport) JRLoader.loadObject(reportStream);
        
            Map parameters = new HashMap();
            parameters.put("ID_Nota", idpemesan);
            
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, new JREmptyDataSource());
            JasperViewer.viewReport(jasperPrint, false);
        }catch(JRException e){
            e.printStackTrace();
        }
       
    }
}


